### ISSUE TITLE
Package search doesn't show the latest version

### ISSUE THREAD

**Issue by jonsa** [ellie-app/ellie#125]
Version `2.1.2` of [`aforemny/material-components-web-elm`](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/) was released a few days ago but Ellie still shows `2.1.0`.

![image](https://user-images.githubusercontent.com/807381/75765895-86423f00-5d40-11ea-8d66-af9a92134a5a.png)

**Comment by MartinSStewart** [comment]
I published `MartinSStewart/elm-audio` a few days ago and haven't seen it either.

**Comment by hpate-omicron** [comment]
I looked into this a bit, and I think it is due to some changes on the package site, in older versions it would return an array of versions, but on the current site, fetching https://package.elm-lang.org/search.json returns an array like

```
[
    {
        "name": "elm/browser",
        "summary": "Run Elm in browsers, with access to browser history for single-page apps (SPAs)",
        "license": "BSD-3-Clause",
        "version": "1.0.2"
    },
    {
        "name": "elm/bytes",
        "summary": "Work with sequences of bytes (a.k.a. ArrayBuffer, typed arrays, DataView)",
        "license": "BSD-3-Clause",
        "version": "1.0.8"
    },
    {
        "name": "elm/core",
        "summary": "Elm's standard libraries",
        "license": "BSD-3-Clause",
        "version": "1.0.5"
    }
]
```

The relevant code looks like it is here https://github.com/ellie-app/ellie/blob/b84c3150992713912dd8f3d8f895f12a51377372/lib/elm/platform/parser.ex#L69

**Comment by friedbrice** [comment]
I'll see if I can do a PR, maybe learn some Elixir in the process ^_^;

**Comment by jhillyerd** [comment]
I'm not sure if it's related, but [mdgriffith/elm-animator](https://package.elm-lang.org/packages/mdgriffith/elm-animator/latest/) is completely missing from the Ellie search results.
