### ISSUE TITLE
Elm bundle returned is corrupt

### ISSUE THREAD

**Issue by PanagiotisGeorgiadis** [ellie-app/ellie#88]
I am trying to write some online examples using the ***wonderful*** ellie-app but I've been experiencing an issue with one of the examples that I am trying to create. ( [example url](https://ellie-app.com/526qHVKNnHLa1) )

As you can see, ellie-app throws two runtime errors. On further investigation, if you open dev tools and navigate to the network tab and check on the `/r/workspace?token=....` request, you'll see that the file that's being served is a partial file hence Javascript is blowing up.

Furthermore the file seems to stop on line 13090 which led me to believe that it could be a **server side limitation on the file size that can be served ( or cached )**.

**Comment by skatkov** [comment]
I'm experiencing similar issue -- stuck on loading window. According to the description that @PanagiotisGeorgiadis  provided, I'm running into a similar issue. 

The only thing that might seem like an error is this strange message about protocol change.

<img width="866" alt="Screenshot 2019-03-19 at 13 10 16" src="https://user-images.githubusercontent.com/544377/54583968-81f61680-4a48-11e9-81ca-0184cbdac7d5.png">

**Comment by tbash** [comment]
Thanks for reporting! This is a deeper issue concerning the `--debug` flag with the Elm compiler, which has been addressed with the core team (see https://github.com/elm/compiler/issues/1851). This will most likely be fixed with the next Elm release. 

You can recreate locally with this as your elm.json: 
```json
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "PanagiotisGeorgiadis/elm-datepicker": "1.0.0",
            "PanagiotisGeorgiadis/elm-datetime": "1.1.0",
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0",
            "elm/time": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.1.3",
            "elm/svg": "1.0.1",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

And the example found in your Ellie as `Main.elm`, then run `elm make src/Main.elm --debug`

You will have the output of: 
```sh
Success! Compiled 1 module.
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal  
```

Checkout https://github.com/ellie-app/ellie/issues/71 and https://github.com/ellie-app/ellie/issues/67 as this is a duplicate issue of those two. 

There is a current feature request open that could help with situations like these that will be the next addition to the Ellie App (see https://github.com/ellie-app/ellie/issues/66). 

Regarding the protocol change, that is totally normal behavior when using WebSocket since `wss` is considered an upgrade from `https` (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#Common_uses_for_this_mechanism).
